<?php
/**
 * AI Content Engine for CitySyncAI
 * Supports multiple providers with caching and preview integration.
 */

function citysyncai_generate_ai_content($provider, $content_type, $city = '') {
    $cache_key = 'citysyncai_' . md5($provider . '_' . $content_type . '_' . $city);
    $cached = get_transient($cache_key);

    echo "<div class='citysyncai-ai-content'>";
    echo "<h3>AI Content Generated by " . ucfirst($provider) . "</h3>";
    if ($city) {
        echo "<p><em>City:</em> " . esc_html($city) . "</p>";
    }
    echo "<p><em>Content type:</em> " . ucfirst($content_type) . "</p>";

    if ($cached) {
        echo "<div class='citysyncai-ai-preview'>{$cached}</div>";
    } else {
        $output = citysyncai_dispatch_ai_provider($provider, $content_type, $city);
        set_transient($cache_key, $output, 30 * DAY_IN_SECONDS); // Extended cache to 30 days
        echo "<div class='citysyncai-ai-preview'>{$output}</div>";
    }

    echo "</div>";
}

function citysyncai_dispatch_ai_provider($provider, $type, $city = '', $custom_prompt = '') {
    // Allow custom prompts for specific use cases (FAQ, testimonials, etc.)
    $has_custom = !empty($custom_prompt);
    
    switch ($provider) {
        case 'openai':
            return $has_custom ? citysyncai_call_openai_custom($custom_prompt) : citysyncai_call_openai($type, $city);
        case 'gemini':
            return $has_custom ? citysyncai_call_gemini_custom($custom_prompt) : citysyncai_call_gemini($type, $city);
        case 'claude':
            return $has_custom ? citysyncai_call_claude_custom($custom_prompt) : citysyncai_call_claude($type, $city);
        case 'deepseek':
            return $has_custom ? citysyncai_call_deepseek_custom($custom_prompt) : citysyncai_call_deepseek($type, $city);
        case 'genspark':
            return $has_custom ? citysyncai_call_genspark_custom($custom_prompt) : citysyncai_call_genspark($type, $city);
        case 'grok':
            return $has_custom ? citysyncai_call_grok_custom($custom_prompt) : citysyncai_call_grok($type, $city);
        default:
            citysyncai_log_error("Unknown AI provider: $provider");
            return "<p class='citysyncai-error'>Unknown provider: $provider</p>";
    }
}

// Custom prompt functions (for FAQ, testimonials, etc.)
function citysyncai_call_gemini_custom($prompt) {
    $api_key = citysyncai_get_gemini_api_key();
    if (empty($api_key)) {
        return '';
    }
    
    $model = get_option('citysyncai_gemini_model', 'gemini-pro');
    $model_map = [
        'gemini-pro' => ['model' => 'gemini-pro', 'version' => 'v1beta'],
        'gemini-1.5-flash' => ['model' => 'gemini-1.5-flash-latest', 'version' => 'v1'],
        'gemini-1.5-pro' => ['model' => 'gemini-1.5-pro-latest', 'version' => 'v1'],
    ];
    
    $model_config = isset($model_map[$model]) ? $model_map[$model] : $model_map['gemini-pro'];
    $selected_model = $model_config['model'];
    $api_version = $model_config['version'];
    
    $body = [
        'contents' => [['parts' => [['text' => $prompt]]]],
        'generationConfig' => [
            'temperature' => 0.7,
            'maxOutputTokens' => 2000,
        ]
    ];
    
    $url = "https://generativelanguage.googleapis.com/{$api_version}/models/{$selected_model}:generateContent?key=" . urlencode($api_key);
    
    return citysyncai_post_to_api($url, $body, null, true);
}

// 🔹 OpenAI
function citysyncai_call_openai($type, $city = '') {
    $api_key = get_option('citysyncai_openai_key', '');
    if (empty($api_key)) {
        return "<p class='citysyncai-error'>OpenAI API key not configured. Please add your API key in Settings → CitySyncAI.</p>";
    }

    $city_context = $city ? " for {$city}" : '';
    $prompt = "Generate SEO-optimized B2B content for a {$type} page{$city_context} targeting BUSINESSES ONLY (NO residential). Focus on enterprise telecom services, business communication solutions, and services for companies spending $1,500-$150,000/month on telecom. Professional tone for business decision-makers.";
    
    $body = [
        'model' => 'gpt-3.5-turbo', // Using cheaper model, can upgrade to gpt-4 if needed
        'messages' => [
            ['role' => 'system', 'content' => 'You are a helpful SEO assistant specializing in local content creation.'],
            ['role' => 'user', 'content' => $prompt],
        ],
        'temperature' => 0.7,
        'max_tokens' => 1000,
    ];
    return citysyncai_post_to_api('https://api.openai.com/v1/chat/completions', $body, $api_key);
}

// 🔹 Gemini with Multi-Account Support
function citysyncai_call_gemini($type, $city = '') {
    // Get API key(s) with rotation support
    $api_key = citysyncai_get_gemini_api_key();
    
    if (empty($api_key)) {
        return "<p class='citysyncai-error'>Gemini API key not configured. Please add your API key in Settings → CitySyncAI. Get your key at <a href='https://makersuite.google.com/app/apikey' target='_blank'>Google AI Studio</a>.</p>";
    }

    $city_context = $city ? " for {$city}" : '';
    $prompt = "Generate comprehensive, SEO-optimized B2B content for a {$type} page{$city_context} focused on BUSINESS TELECOM SERVICES ONLY (NO residential services). 

Target audience: Businesses spending $1,500-$150,000 per month on telecom services. Focus on enterprise communication solutions, business phone systems, internet connectivity for businesses, cloud services, unified communications, and related business telecom needs.

Write in a professional, B2B-focused tone suitable for business decision-makers and IT managers. Include relevant local business information, economic data, and business-friendly aspects of the area. Emphasize enterprise solutions, reliability, scalability, and cost-effectiveness for businesses.

DO NOT mention residential services, home internet, or consumer-focused offerings. This is exclusively for business-to-business (B2B) services.";
    
    // Get model setting, default to gemini-pro for compatibility
    $model = get_option('citysyncai_gemini_model', 'gemini-pro');
    $model_map = [
        'gemini-pro' => ['model' => 'gemini-pro', 'version' => 'v1beta'], // Most compatible
        'gemini-1.5-flash' => ['model' => 'gemini-1.5-flash-latest', 'version' => 'v1'],
        'gemini-1.5-pro' => ['model' => 'gemini-1.5-pro-latest', 'version' => 'v1'],
    ];
    
    $model_config = isset($model_map[$model]) ? $model_map[$model] : $model_map['gemini-pro'];
    $selected_model = $model_config['model'];
    $api_version = $model_config['version'];
    
    $body = [
        'contents' => [
            [
                'parts' => [
                    ['text' => $prompt]
                ]
            ]
        ],
        'generationConfig' => [
            'temperature' => 0.7,
            'maxOutputTokens' => 2000,
        ]
    ];
    
    $url = "https://generativelanguage.googleapis.com/{$api_version}/models/{$selected_model}:generateContent?key=" . urlencode($api_key);
    
    return citysyncai_post_to_api($url, $body, null, true);
}

/**
 * Get Gemini API key with rotation support
 * Rotates between primary and secondary keys if multi-account is enabled
 *
 * @return string API key
 */
function citysyncai_get_gemini_api_key() {
    $use_multi = get_option('citysyncai_use_multi_account', 'no') === 'yes';
    $key_1 = get_option('citysyncai_gemini_key', '');
    $key_2 = get_option('citysyncai_gemini_key_2', '');
    
    // If multi-account is enabled and both keys exist, rotate
    if ($use_multi && !empty($key_1) && !empty($key_2)) {
        $rotation_count = (int) get_option('citysyncai_gemini_rotation_count', 0);
        $rotation_count++;
        update_option('citysyncai_gemini_rotation_count', $rotation_count);
        
        // Alternate between keys (every request, or you can make it every N requests)
        return ($rotation_count % 2 === 0) ? $key_2 : $key_1;
    }
    
    // Otherwise use primary key
    return $key_1;
}

// 🔹 Claude
function citysyncai_call_claude($type, $city = '') {
    $api_key = get_option('citysyncai_claude_key', '');
    if (empty($api_key)) {
        return "<p class='citysyncai-error'>Claude API key not configured. Please add your API key in Settings → CitySyncAI.</p>";
    }

    $city_context = $city ? " for {$city}" : '';
    $prompt = "Generate SEO-optimized B2B content for a {$type} page{$city_context} targeting BUSINESSES ONLY (NO residential). Focus on enterprise telecom services, business communication solutions, and services for companies spending $1,500-$150,000/month on telecom. Professional tone for business decision-makers.";
    
    $body = [
        'model' => 'claude-3-haiku-20240307', // Using cheaper model
        'max_tokens' => 1000,
        'temperature' => 0.7,
        'messages' => [
            ['role' => 'user', 'content' => $prompt],
        ],
    ];
    return citysyncai_post_to_api('https://api.anthropic.com/v1/messages', $body, $api_key, false, [
        'x-api-key' => $api_key,
        'anthropic-version' => '2023-06-01'
    ]);
}

// 🔹 DeepSeek (VERY AFFORDABLE - Great for bulk generation - RECOMMENDED)
function citysyncai_call_deepseek($type, $city = '') {
    $api_key = citysyncai_get_deepseek_api_key();
    if (empty($api_key)) {
        return "<p class='citysyncai-error'>DeepSeek API key not configured. Please add your API key in Settings → CitySyncAI. Get your key at <a href='https://platform.deepseek.com/' target='_blank'>DeepSeek Platform</a> (very affordable: $0.14/1M tokens).</p>";
    }

    // Get city data for richer context
    $city_parts = explode(', ', $city);
    $city_name = $city_parts[0] ?? '';
    $state = $city_parts[1] ?? '';
    $city_data = citysyncai_get_city_data($city_name, $state);
    $population = $city_data['population'] ?? '';
    $population_text = $population ? " (Population: " . number_format($population) . ")" : '';
    
    $prompt = "Write a comprehensive, high-quality, conversion-focused business telecom services article (2500-3000 words) for {$city}{$population_text}.

**TARGET AUDIENCE:** Business owners, IT managers, and decision-makers at companies spending $1,500-$150,000/month on telecom services.

**CRITICAL REQUIREMENTS:**
- EXCLUSIVELY B2B - NEVER mention residential services, home internet, or consumer offerings
- Use HTML formatting: <h2>, <h3>, <p>, <ul>, <li>, <strong> - NO markdown
- Professional, authoritative, conversion-focused tone
- 2500-3000 words minimum
- Include specific examples, statistics, and actionable advice

**REQUIRED STRUCTURE:**

<h2>Business Fiber Internet in {$city} - Complete Enterprise Guide</h2>
<p>[Strong opening paragraph - 3-4 sentences emphasizing same-day availability checking, comparing 50+ carriers, free service, no obligation. Include trust signals: 25 years in business, 2,740+ clients served.]</p>

<h2>Why Businesses in {$city} Need Enterprise Telecom Solutions</h2>
<p>[2-3 paragraphs about local business landscape, economic growth, industries present. Include specific statistics if available. Explain why reliable telecom is critical for {$city} businesses.]</p>

<h2>Complete Business Telecom Services We Offer in {$city}</h2>

<h3>Business Fiber Internet - High-Speed Connectivity</h3>
<p>[Detailed paragraph about fiber benefits: symmetrical speeds, reliability, scalability. Emphasize availability checking and carrier comparison.]</p>

<h3>Enterprise Phone Systems</h3>
<p>[VoIP, PBX systems, unified communications. Advanced features for modern businesses.]</p>

<h3>Dedicated Internet & Ethernet</h3>
<p>[Business-grade connectivity, SLAs, guaranteed bandwidth, uptime guarantees.]</p>

<h3>Cloud Services & Hosted Solutions</h3>
<p>[Cloud infrastructure, data storage, disaster recovery, security, scalability.]</p>

<h3>Unified Communications Platform</h3>
<p>[Integrated voice, video, messaging, collaboration tools. Remote team support.]</p>

<h3>Network Security & Managed Services</h3>
<p>[Enterprise security, monitoring, 24/7 support, proactive management.]</p>

<h2>Why Choose Us for Business Telecom in {$city}?</h2>
<ul>
<li><strong>25 Years Experience:</strong> We've helped thousands of businesses optimize their telecom</li>
<li><strong>2,740+ Clients:</strong> Trusted by businesses nationwide</li>
<li><strong>50+ Carrier Partners:</strong> Compare all options to find best pricing</li>
<li><strong>Same-Day Availability:</strong> Free checks with immediate results</li>
<li><strong>Local Expertise:</strong> Understanding of {$city} business landscape</li>
<li><strong>Scalable Solutions:</strong> Grow with your business needs</li>
</ul>

<h2>Industries We Serve in {$city}</h2>
<p>[Detailed paragraphs covering: Manufacturing, Healthcare, Technology, Logistics, Professional Services - with specific use cases for each]</p>

<h2>The ROI of Modern Telecom Infrastructure for {$city} Businesses</h2>
<p>[2-3 paragraphs about cost savings, efficiency gains, competitive advantages, ROI examples]</p>

<h2>Get Started - Check Fiber Availability in {$city} Today</h2>
<p>[Strong call-to-action: Free availability check, same-day results, compare all carriers, no obligation. Include phone number: 850-359-8004]</p>

**WRITING STYLE:**
- Use persuasive, benefit-focused language
- Include specific numbers and examples
- Avoid generic fluff - every sentence adds value
- Power words: comprehensive, enterprise-grade, guaranteed, dedicated, cutting-edge
- Natural keyword integration (don't stuff keywords)
- Write for humans first, SEO second

**OUTPUT:** Generate the complete article in HTML format following this exact structure.";
    
    $body = [
        'model' => 'deepseek-chat',
        'messages' => [
            ['role' => 'system', 'content' => 'You are an expert B2B content writer specializing in telecom services. You create high-quality, conversion-focused articles that rank well in search engines and convert visitors into leads.'],
            ['role' => 'user', 'content' => $prompt],
        ],
        'temperature' => 0.7,
        'max_tokens' => 4000, // Increased for longer, better content
        'stream' => false,
    ];
    return citysyncai_post_to_api('https://api.deepseek.com/v1/chat/completions', $body, $api_key);
}

/**
 * Get DeepSeek API key with rotation support (if multiple keys added later)
 *
 * @return string API key
 */
function citysyncai_get_deepseek_api_key() {
    // For now, just return primary key
    // Can add rotation logic later if needed
    return get_option('citysyncai_deepseek_key', '');
}

// Custom prompt function for DeepSeek (FAQs, testimonials, etc.)
function citysyncai_call_deepseek_custom($prompt) {
    $api_key = citysyncai_get_deepseek_api_key();
    if (empty($api_key)) {
        return '';
    }
    
    $body = [
        'model' => 'deepseek-chat',
        'messages' => [
            ['role' => 'system', 'content' => 'You are a helpful SEO assistant specializing in B2B telecom content.'],
            ['role' => 'user', 'content' => $prompt],
        ],
        'temperature' => 0.7,
        'max_tokens' => 1800, // Reduced to speed up generation
        'stream' => false,
    ];
    
    return citysyncai_post_to_api('https://api.deepseek.com/v1/chat/completions', $body, $api_key);
}

// 🔹 Genspark
function citysyncai_call_genspark($type, $city = '') {
    $api_key = get_option('citysyncai_genspark_key', '');
    if (empty($api_key)) {
        return "<p class='citysyncai-error'>Genspark API key not configured. Please add your API key in Settings → CitySyncAI.</p>";
    }

    $city_context = $city ? " for {$city}" : '';
    $prompt = "Generate SEO-optimized content for a {$type} page{$city_context} targeting local users.";
    
    $body = [
        'model' => 'genspark-pro',
        'messages' => [
            ['role' => 'user', 'content' => $prompt],
        ],
    ];
    return citysyncai_post_to_api('https://api.genspark.ai/v1/chat/completions', $body, $api_key);
}

// 🔹 Grok
function citysyncai_call_grok($type, $city = '') {
    $api_key = get_option('citysyncai_grok_key', '');
    if (empty($api_key)) {
        return "<p class='citysyncai-error'>Grok API key not configured. Please add your API key in Settings → CitySyncAI.</p>";
    }

    // Get city data for richer context
    $city_parts = explode(', ', $city);
    $city_name = $city_parts[0] ?? '';
    $state = $city_parts[1] ?? '';
    $city_data = citysyncai_get_city_data($city_name, $state);
    $population = $city_data['population'] ?? '';
    $population_text = $population ? " (Population: " . number_format($population) . ")" : '';
    
    $prompt = "Write a comprehensive, high-quality, conversion-focused business telecom services article (2500-3000 words) for {$city}{$population_text}.

**TARGET AUDIENCE:** Business owners, IT managers, and decision-makers at companies spending $1,500-$150,000/month on telecom services.

**CRITICAL REQUIREMENTS:**
- EXCLUSIVELY B2B - NEVER mention residential services, home internet, or consumer offerings
- Use HTML formatting: <h2>, <h3>, <p>, <ul>, <li>, <strong> - NO markdown
- Professional, authoritative, conversion-focused tone
- 2500-3000 words minimum
- Include specific examples, statistics, and actionable advice

**REQUIRED STRUCTURE:**

<h2>Business Fiber Internet in {$city} - Complete Enterprise Guide</h2>
<p>[Strong opening paragraph - 3-4 sentences emphasizing same-day availability checking, comparing 50+ carriers, free service, no obligation. Include trust signals: 25 years in business, 2,740+ clients served.]</p>

<h2>Why Businesses in {$city} Need Enterprise Telecom Solutions</h2>
<p>[2-3 paragraphs about local business landscape, economic growth, industries present. Include specific statistics if available. Explain why reliable telecom is critical for {$city} businesses.]</p>

<h2>Complete Business Telecom Services We Offer in {$city}</h2>

<h3>Business Fiber Internet - High-Speed Connectivity</h3>
<p>[Detailed paragraph about fiber benefits: symmetrical speeds, reliability, scalability. Emphasize availability checking and carrier comparison.]</p>

<h3>Enterprise Phone Systems</h3>
<p>[VoIP, PBX systems, unified communications. Advanced features for modern businesses.]</p>

<h3>Dedicated Internet & Ethernet</h3>
<p>[Business-grade connectivity, SLAs, guaranteed bandwidth, uptime guarantees.]</p>

<h3>Cloud Services & Hosted Solutions</h3>
<p>[Cloud infrastructure, data storage, disaster recovery, security, scalability.]</p>

<h3>Unified Communications Platform</h3>
<p>[Integrated voice, video, messaging, collaboration tools. Remote team support.]</p>

<h3>Network Security & Managed Services</h3>
<p>[Enterprise security, monitoring, 24/7 support, proactive management.]</p>

<h2>Why Choose Us for Business Telecom in {$city}?</h2>
<ul>
<li><strong>25 Years Experience:</strong> We've helped thousands of businesses optimize their telecom</li>
<li><strong>2,740+ Clients:</strong> Trusted by businesses nationwide</li>
<li><strong>50+ Carrier Partners:</strong> Compare all options to find best pricing</li>
<li><strong>Same-Day Availability:</strong> Free checks with immediate results</li>
<li><strong>Local Expertise:</strong> Understanding of {$city} business landscape</li>
<li><strong>Scalable Solutions:</strong> Grow with your business needs</li>
</ul>

<h2>Industries We Serve in {$city}</h2>
<p>[Detailed paragraphs covering: Manufacturing, Healthcare, Technology, Logistics, Professional Services - with specific use cases for each]</p>

<h2>The ROI of Modern Telecom Infrastructure for {$city} Businesses</h2>
<p>[2-3 paragraphs about cost savings, efficiency gains, competitive advantages, ROI examples]</p>

<h2>Get Started - Check Fiber Availability in {$city} Today</h2>
<p>[Strong call-to-action: Free availability check, same-day results, compare all carriers, no obligation. Include phone number: 850-359-8004]</p>

**WRITING STYLE:**
- Use persuasive, benefit-focused language
- Include specific numbers and examples
- Avoid generic fluff - every sentence adds value
- Power words: comprehensive, enterprise-grade, guaranteed, dedicated, cutting-edge
- Natural keyword integration (don't stuff keywords)
- Write for humans first, SEO second

**OUTPUT:** Generate the complete article in HTML format following this exact structure.";
    
    $body = [
        'model' => 'grok-3',
        'messages' => [
            ['role' => 'system', 'content' => 'You are an expert B2B content writer specializing in telecom services. You create high-quality, conversion-focused articles that rank well in search engines and convert visitors into leads.'],
            ['role' => 'user', 'content' => $prompt],
        ],
        'temperature' => 0.7,
        'max_tokens' => 4000, // Increased for longer, better content
    ];
    return citysyncai_post_to_api('https://api.x.ai/v1/chat/completions', $body, $api_key);
}

// Custom prompt function for Grok (FAQs, testimonials, etc.)
function citysyncai_call_grok_custom($prompt) {
    $api_key = get_option('citysyncai_grok_key', '');
    if (empty($api_key)) {
        return '';
    }
    
    $body = [
        'model' => 'grok-3', // Updated: grok-beta was deprecated on 2025-09-15
        'messages' => [
            ['role' => 'system', 'content' => 'You are a helpful SEO assistant specializing in B2B telecom content.'],
            ['role' => 'user', 'content' => $prompt],
        ],
        'temperature' => 0.7,
        'max_tokens' => 2000,
    ];
    
    return citysyncai_post_to_api('https://api.x.ai/v1/chat/completions', $body, $api_key);
}

// 🔧 Shared API Caller with Enhanced Error Handling
function citysyncai_post_to_api($url, $body, $api_key = null, $is_gemini = false, $custom_headers = []) {
    // Increase PHP execution time limit for this request (if allowed)
    // This helps prevent server-level timeouts from overriding WordPress timeout
    if (function_exists('set_time_limit') && ini_get('safe_mode') == 0) {
        @set_time_limit(120); // 2 minutes for PHP execution time
    }
    
    // Build headers
    if (!empty($custom_headers)) {
        $headers = array_merge(['Content-Type' => 'application/json'], $custom_headers);
    } else {
        $headers = [
            'Content-Type' => 'application/json',
        ];
        if ($api_key && !$is_gemini) {
            $headers['Authorization'] = 'Bearer ' . $api_key;
        }
    }

    // Use longer timeout for AI APIs (especially DeepSeek which can be slower)
    // 90 seconds should be enough for most API calls, including longer content generation
    // Note: Server-level PHP max_execution_time may override this
    $timeout = 90;
    
    $response = wp_remote_post($url, [
        'headers' => $headers,
        'body'    => wp_json_encode($body),
        'timeout' => $timeout,
        'stream' => false, // Don't stream - wait for complete response
        'blocking' => true, // Block until response is received
    ]);

    // Check for WordPress HTTP errors
    if (is_wp_error($response)) {
        $error_code = $response->get_error_code();
        $error_msg = $response->get_error_message();
        
        citysyncai_log_error("API Request Error ({$error_code}): {$error_msg}");
        
        // Provide helpful error messages for common issues
        if ($error_code === 'http_request_failed' && (strpos($error_msg, 'timeout') !== false || strpos($error_msg, 'timed out') !== false)) {
            return "<p class='citysyncai-error'><strong>Request Timeout:</strong> The API request took too long (>90 seconds). This can happen if:<br>
            • The API is experiencing slow response times<br>
            • Your server has network connectivity issues<br>
            • The content generation is taking longer than expected<br><br>
            <strong>Try:</strong> Click the preview again, or try a different AI provider (Grok, Gemini if available).</p>";
        }
        
        return "<p class='citysyncai-error'>API Error ({$error_code}): " . esc_html($error_msg) . "</p>";
    }

    $response_code = wp_remote_retrieve_response_code($response);
    $response_body = wp_remote_retrieve_body($response);
    $data = json_decode($response_body, true);

    // Check HTTP status code
    if ($response_code !== 200) {
        $error_message = isset($data['error']['message']) ? $data['error']['message'] : 'Unknown error';
        if (isset($data['error'])) {
            $error_message = is_array($data['error']) ? (isset($data['error']['message']) ? $data['error']['message'] : wp_json_encode($data['error'])) : $data['error'];
        }
        citysyncai_log_error("API HTTP Error {$response_code}: {$error_message}");
        return "<p class='citysyncai-error'>API Error ({$response_code}): " . esc_html($error_message) . "</p>";
    }

    // Parse Gemini response
    if ($is_gemini) {
        // Handle API errors first
        if (isset($data['error'])) {
            $error_msg = $data['error']['message'] ?? 'Unknown Gemini API error';
            citysyncai_log_error("Gemini API Error: {$error_msg}");
            citysyncai_log_api_usage('gemini', 'error');
            
            // If model not found, try fallback to gemini-pro
            if (strpos($error_msg, 'not found') !== false || strpos($error_msg, 'not supported') !== false) {
                return "<p class='citysyncai-error'>Gemini API Error: {$error_msg}. Please try selecting 'Gemini Pro' model instead.</p>";
            }
            
            return "<p class='citysyncai-error'>Gemini API Error: " . esc_html($error_msg) . "</p>";
        }
        
        if (!isset($data['candidates'][0]['content']['parts'][0]['text'])) {
            $error_msg = isset($data['error']['message']) ? $data['error']['message'] : 'No text in Gemini response';
            citysyncai_log_error("Gemini API Error: {$error_msg}");
            citysyncai_log_api_usage('gemini', 'error');
            return "<p class='citysyncai-error'>Gemini API Error: " . esc_html($error_msg) . "</p>";
        }
        citysyncai_log_api_usage('gemini', 'success');
        return wp_kses_post($data['candidates'][0]['content']['parts'][0]['text']);
    }

    // Parse standard OpenAI-compatible response
    if (!isset($data['choices'][0]['message']['content'])) {
        $error_msg = isset($data['error']['message']) ? $data['error']['message'] : 'No content in API response';
        citysyncai_log_error("API Response Error: {$error_msg}");
        // Try to detect provider from URL for logging
        $provider = 'unknown';
        if (strpos($url, 'openai.com') !== false) $provider = 'openai';
        elseif (strpos($url, 'deepseek.com') !== false) $provider = 'deepseek';
        elseif (strpos($url, 'anthropic.com') !== false) $provider = 'claude';
        elseif (strpos($url, 'x.ai') !== false) $provider = 'grok';
        citysyncai_log_api_usage($provider, 'error');
        return "<p class='citysyncai-error'>API Response Error: " . esc_html($error_msg) . "</p>";
    }
    
    // Log successful API usage
    $provider = 'unknown';
    if (strpos($url, 'openai.com') !== false) $provider = 'openai';
    elseif (strpos($url, 'deepseek.com') !== false) $provider = 'deepseek';
    elseif (strpos($url, 'anthropic.com') !== false) $provider = 'claude';
    elseif (strpos($url, 'x.ai') !== false) $provider = 'grok';
    citysyncai_log_api_usage($provider, 'success');

    return wp_kses_post($data['choices'][0]['message']['content']);
}

// Note: Logging is handled by includes/log-engine.php