<?php
/**
 * Plugin Name: CitySyncAI
 * Description: Dynamically generate SEO-optimized city pages using AI-powered content.
 * Version: 1.0.0
 * Author: John Masoner
 * License: MIT
 */

defined('ABSPATH') || exit;

// Load core modules
require_once plugin_dir_path(__FILE__) . 'includes/admin-settings.php';
require_once plugin_dir_path(__FILE__) . 'includes/page-generator.php';
require_once plugin_dir_path(__FILE__) . 'includes/ai-content-engine.php';
require_once plugin_dir_path(__FILE__) . 'includes/schema-engine.php';
require_once plugin_dir_path(__FILE__) . 'schema-sitemap.php';

// Register shortcode
add_shortcode('citysyncai', 'citysyncai_shortcode_handler');
add_shortcode('citysyncai', 'citysyncai_render_schema_output');

// Register REST API
add_action('rest_api_init', function () {
    register_rest_route('citysyncai/v1', '/generate', [
        'methods' => 'POST',
        'callback' => 'citysyncai_rest_generate',
        'permission_callback' => '__return_true',
    ]);
});
add_action('rest_api_init', function () {
    register_rest_route('citysyncai/v1', '/schema', [
        'methods' => 'GET',
        'callback' => 'citysyncai_rest_schema_export',
        'permission_callback' => '__return_true',
    ]);
});
add_action('rest_api_init', function () {
    register_rest_route('citysyncai/v1', '/schema/generate', [
        'methods' => 'POST',
        'callback' => 'citysyncai_generate_schema_from_ai',
        'permission_callback' => '__return_true',
    ]);
});
register_activation_hook(__FILE__, function () {
    flush_rewrite_rules();
});
register_deactivation_hook(__FILE__, function () {
    flush_rewrite_rules();
});
function citysyncai_render_schema_output() {
    $schema_type = get_option('citysyncai_schema_type', 'LocalBusiness');
    $enable_ai   = get_option('citysyncai_enable_ai', 'no');
    $provider    = get_option('citysyncai_ai_provider', 'openai');
    $content_type = get_option('citysyncai_content_type', 'overview');

    // Load schema template
    $template_path = plugin_dir_path(__FILE__) . 'templates/schema-' . strtolower($schema_type) . '.php';
    if (file_exists($template_path)) {
        include $template_path;
    } else {
        echo "<!-- Schema template not found: $schema_type -->";
    }

    // Trigger AI content if enabled
    if ($enable_ai === 'yes') {
        citysyncai_generate_ai_content($provider, $content_type);
    }
}
function citysyncai_generate_ai_content($provider, $content_type) {
    echo "<div class='citysyncai-ai-content'>";
    echo "<h3>AI Content Generated by " . ucfirst($provider) . "</h3>";
    echo "<p><em>Content type:</em> " . ucfirst($content_type) . "</p>";

    // Placeholder logic — replace with actual API calls later
    echo "<p>[Simulated AI output for $content_type using $provider]</p>";
    echo "</div>";
}