INSERT INTO cities (city_name, state_code, state_name, population, nearby_cities) VALUES
('Austin', 'TX', 'Texas', 961855, ARRAY['San Antonio', 'Dallas', 'Houston']),
('Denver', 'CO', 'Colorado', 727211, ARRAY['Aurora', 'Lakewood', 'Arvada']),
('Seattle', 'WA', 'Washington', 753675, ARRAY['Tacoma', 'Bellevue', 'Redmond']),
('Los Angeles', 'CA', 'California', 3979576, ARRAY['Long Beach', 'Anaheim', 'Santa Ana']),
('New York', 'NY', 'New York', 8336817, ARRAY['Newark', 'Jersey City', 'Yonkers']),
('Chicago', 'IL', 'Illinois', 2693976, ARRAY['Evanston', 'Oak Park', 'Naperville']),
('Boston', 'MA', 'Massachusetts', 692600, ARRAY['Cambridge', 'Brookline', 'Somerville']),
('Atlanta', 'GA', 'Georgia', 498715, ARRAY['Marietta', 'Sandy Springs', 'Decatur']),
('Miami', 'FL', 'Florida', 442241, ARRAY['Fort Lauderdale', 'Hollywood', 'Coral Gables']),
('Phoenix', 'AZ', 'Arizona', 1624569, ARRAY['Glendale', 'Chandler', 'Scottsdale']),
('San Francisco', 'CA', 'California', 873965, ARRAY['Oakland', 'Berkeley', 'Daly City']),
('Portland', 'OR', 'Oregon', 652032, ARRAY['Gresham', 'Beaverton', 'Lake Oswego']),
('Nashville', 'TN', 'Tennessee', 678889, ARRAY['Brentwood', 'Franklin', 'Spring Hill']),
('Houston', 'TX', 'Texas', 2302878, ARRAY['Spring', 'Pearland', 'Sugar Land']),
('San Diego', 'CA', 'California', 1386932, ARRAY['Chula Vista', 'Oceanside', 'Escondido']),
('Philadelphia', 'PA', 'Pennsylvania', 1605602, ARRAY['Chester', 'Norriton', 'Cheltenham']),
('Dallas', 'TX', 'Texas', 1343573, ARRAY['Arlington', 'Plano', 'Irving']),
('San Jose', 'CA', 'California', 1009408, ARRAY['Sunnyvale', 'Cupertino', 'Santa Clara']),
('Minneapolis', 'MN', 'Minnesota', 398552, ARRAY['St. Paul', 'Edina', 'Bloomington']),
('Detroit', 'MI', 'Michigan', 639111, ARRAY['Hamtramck', 'Highland Park', 'Dearborn']),
('Charlotte', 'NC', 'North Carolina', 891733, ARRAY['Concord', 'Kannapolis', 'Cabarrus County']),
('Raleigh', 'NC', 'North Carolina', 474069, ARRAY['Cary', 'Durham', 'Wake Forest']),
('Memphis', 'TN', 'Tennessee', 633104, ARRAY['Shelby County', 'Germantown', 'Collierville']),
('Washington', 'DC', 'District of Columbia', 689545, ARRAY['Arlington', 'Alexandria', 'Bethesda']),
('Tucson', 'AZ', 'Arizona', 541811, ARRAY['Oro Valley', 'South Tucson', 'Sahuarita']),
('Albuquerque', 'NM', 'New Mexico', 562595, ARRAY['Rio Rancho', 'Bernalillo', 'Corrales']),
('Fresno', 'CA', 'California', 525010, ARRAY['Clovis', 'Selma', 'Reedley']),
('Sacramento', 'CA', 'California', 525170, ARRAY['Folsom', 'Rancho Cordova', 'Carmichael']),
('Kansas City', 'MO', 'Missouri', 481420, ARRAY['Overland Park', 'Independence', 'Lee''s Summit']),
('Toledo', 'OH', 'Ohio', 271605, ARRAY['Oregon', 'Maumee', 'Sylvania']),
('Long Beach', 'CA', 'California', 466742, ARRAY['Los Angeles', 'Anaheim', 'Compton']),
('Fort Worth', 'TX', 'Texas', 918915, ARRAY['Arlington', 'Grand Prairie', 'Irving']),
('Chandler', 'AZ', 'Arizona', 278026, ARRAY['Tempe', 'Gilbert', 'Phoenix']),
('Orlando', 'FL', 'Florida', 307573, ARRAY['Kissimmee', 'Sanford', 'Ocoee']),
('Laredo', 'TX', 'Texas', 256394, ARRAY['Nueva Laredo', 'Rio Bravo', 'San Ygnacio']),
('Plano', 'TX', 'Texas', 287862, ARRAY['Dallas', 'Richardson', 'Frisco']),
('Irvine', 'CA', 'California', 307670, ARRAY['Newport Beach', 'Tustin', 'Laguna Hills']),
('Corpus Christi', 'TX', 'Texas', 305215, ARRAY['Kingsville', 'Flour Bluff', 'Robstown']),
('Cincinnati', 'OH', 'Ohio', 309317, ARRAY['Norwood', 'Newport', 'Florence']),
('St. Louis', 'MO', 'Missouri', 301578, ARRAY['Clayton', 'Webster Groves', 'Kirkwood']),
('Madison', 'WI', 'Wisconsin', 269840, ARRAY['Fitchburg', 'Dane County', 'Monona']),
('Lexington', 'KY', 'Kentucky', 322570, ARRAY['Nicholasville', 'Richmond', 'Georgetown']),
('Louisville', 'KY', 'Kentucky', 256231, ARRAY['Jeffersontown', 'St. Matthews', 'La Grange']),
('Stockton', 'CA', 'California', 330281, ARRAY['Lodi', 'Tracy', 'Manteca']),
('Cincinnati', 'OH', 'Ohio', 309317, ARRAY['Norwood', 'Newport', 'Florence']),
('Baton Rouge', 'LA', 'Louisiana', 227818, ARRAY['Central', 'Baker', 'Zachary']),
('St. Paul', 'MN', 'Minnesota', 311527, ARRAY['Minneapolis', 'Maplewood', 'Falcon Heights']),
('Anchorage', 'AK', 'Alaska', 291826, ARRAY['Juneau', 'Fairbanks', 'Sitka']),
('New Orleans', 'LA', 'Louisiana', 383997, ARRAY['Metairie', 'Kenner', 'Gretna']),
('Buffalo', 'NY', 'New York', 250604, ARRAY['Cheektowaga', 'Niagara Falls', 'Tonawanda']),
('Henderson', 'NV', 'Nevada', 317610, ARRAY['Las Vegas', 'Boulder City', 'Pahrump']),
('Riverside', 'CA', 'California', 265637, ARRAY['San Bernardino', 'Moreno Valley', 'Victorville']),
('Toledo', 'OH', 'Ohio', 271605, ARRAY['Oregon', 'Maumee', 'Sylvania']),
('Greensboro', 'NC', 'North Carolina', 294723, ARRAY['High Point', 'Asheboro', 'Kernersville']),
('Garland', 'TX', 'Texas', 239928, ARRAY['Dallas', 'Arlington', 'Irving']),
('Glendale', 'CA', 'California', 196543, ARRAY['Los Angeles', 'Burbank', 'Pasadena']),
('Irving', 'TX', 'Texas', 238080, ARRAY['Dallas', 'Arlington', 'Fort Worth']),
('Spokane', 'WA', 'Washington', 223164, ARRAY['Spokane Valley', 'Cheney', 'Liberty']),
('Gilbert', 'AZ', 'Arizona', 267918, ARRAY['Chandler', 'Mesa', 'Queen Creek']),
('Boise', 'ID', 'Idaho', 235684, ARRAY['Meridian', 'Nampa', 'Eagle']),
('Huntsville', 'AL', 'Alabama', 215006, ARRAY['Madison', 'Decatur', 'Limestone']),
('Des Moines', 'IA', 'Iowa', 214237, ARRAY['West Des Moines', 'Ankeny', 'Urbandale']),
('Modesto', 'CA', 'California', 218464, ARRAY['Ceres', 'Turlock', 'Ripon']),
('Shreveport', 'LA', 'Louisiana', 189874, ARRAY['Bossier City', 'Blanchard', 'Haughton']),
('Glendale', 'AZ', 'Arizona', 247901, ARRAY['Phoenix', 'Peoria', 'Avondale']),
('Fontana', 'CA', 'California', 222309, ARRAY['Rialto', 'San Bernardino', 'Ontario']),
('Louisville', 'KY', 'Kentucky', 256231, ARRAY['Jeffersontown', 'St. Matthews', 'La Grange']),
('Montgomery', 'AL', 'Alabama', 195111, ARRAY['Birmingham', 'Dothan', 'Auburn']),
('Ft. Worth', 'TX', 'Texas', 918915, ARRAY['Arlington', 'Grand Prairie', 'Irving']),
('Amarillo', 'TX', 'Texas', 199371, ARRAY['Canyon', 'Randall County', 'Lubbock']),
('Moreno Valley', 'CA', 'California', 210541, ARRAY['Riverside', 'San Bernardino', 'Victorville']),
('Huntington Beach', 'CA', 'California', 194282, ARRAY['Newport Beach', 'Fountain Valley', 'Garden Grove']),
('Atlanta', 'GA', 'Georgia', 498715, ARRAY['Marietta', 'Sandy Springs', 'Decatur']),
('Newark', 'NJ', 'New Jersey', 311549, ARRAY['Jersey City', 'East Orange', 'Irvington']),
('Grand Prairie', 'TX', 'Texas', 192302, ARRAY['Arlington', 'Irving', 'Fort Worth']),
('Dallas', 'TX', 'Texas', 1343573, ARRAY['Arlington', 'Plano', 'Irving']);

SELECT COUNT(*) as cities_imported, COUNT(DISTINCT state_code) as states FROM cities;
