<?php
/**
 * AI Content Engine for CitySyncAI
 * Supports multiple providers with caching and preview integration.
 */

function citysyncai_generate_ai_content($provider, $content_type, $city = '') {
    $cache_key = 'citysyncai_' . md5($provider . '_' . $content_type . '_' . $city);
    $cached = get_transient($cache_key);

    echo "<div class='citysyncai-ai-content'>";
    echo "<h3>AI Content Generated by " . ucfirst($provider) . "</h3>";
    if ($city) {
        echo "<p><em>City:</em> " . esc_html($city) . "</p>";
    }
    echo "<p><em>Content type:</em> " . ucfirst($content_type) . "</p>";

    if ($cached) {
        echo "<div class='citysyncai-ai-preview'>{$cached}</div>";
    } else {
        $output = citysyncai_dispatch_ai_provider($provider, $content_type, $city);
        set_transient($cache_key, $output, 30 * DAY_IN_SECONDS); // Extended cache to 30 days
        echo "<div class='citysyncai-ai-preview'>{$output}</div>";
    }

    echo "</div>";
}

function citysyncai_dispatch_ai_provider($provider, $type, $city = '', $custom_prompt = '') {
    // Allow custom prompts for specific use cases (FAQ, testimonials, etc.)
    $has_custom = !empty($custom_prompt);
    
    switch ($provider) {
        case 'openai':
            return $has_custom ? citysyncai_call_openai_custom($custom_prompt) : citysyncai_call_openai($type, $city);
        case 'gemini':
            return $has_custom ? citysyncai_call_gemini_custom($custom_prompt) : citysyncai_call_gemini($type, $city);
        case 'claude':
            return $has_custom ? citysyncai_call_claude_custom($custom_prompt) : citysyncai_call_claude($type, $city);
        case 'deepseek':
            return $has_custom ? citysyncai_call_deepseek_custom($custom_prompt) : citysyncai_call_deepseek($type, $city);
        case 'genspark':
            return $has_custom ? citysyncai_call_genspark_custom($custom_prompt) : citysyncai_call_genspark($type, $city);
        case 'grok':
            return $has_custom ? citysyncai_call_grok_custom($custom_prompt) : citysyncai_call_grok($type, $city);
        default:
            citysyncai_log_error("Unknown AI provider: $provider");
            return "<p class='citysyncai-error'>Unknown provider: $provider</p>";
    }
}

// Custom prompt functions (for FAQ, testimonials, etc.)
function citysyncai_call_gemini_custom($prompt) {
    $api_key = citysyncai_get_gemini_api_key();
    if (empty($api_key)) {
        return '';
    }
    
    $model = get_option('citysyncai_gemini_model', 'gemini-1.5-flash');
    $body = [
        'contents' => [['parts' => [['text' => $prompt]]]],
        'generationConfig' => [
            'temperature' => 0.7,
            'maxOutputTokens' => 2000,
        ]
    ];
    
    return citysyncai_post_to_api("https://generativelanguage.googleapis.com/v1beta/models/{$model}:generateContent?key=" . urlencode($api_key), $body, null, true);
}

// 🔹 OpenAI
function citysyncai_call_openai($type, $city = '') {
    $api_key = get_option('citysyncai_openai_key', '');
    if (empty($api_key)) {
        return "<p class='citysyncai-error'>OpenAI API key not configured. Please add your API key in Settings → CitySyncAI.</p>";
    }

    $city_context = $city ? " for {$city}" : '';
    $prompt = "Generate SEO-optimized B2B content for a {$type} page{$city_context} targeting BUSINESSES ONLY (NO residential). Focus on enterprise telecom services, business communication solutions, and services for companies spending $1,500-$150,000/month on telecom. Professional tone for business decision-makers.";
    
    $body = [
        'model' => 'gpt-3.5-turbo', // Using cheaper model, can upgrade to gpt-4 if needed
        'messages' => [
            ['role' => 'system', 'content' => 'You are a helpful SEO assistant specializing in local content creation.'],
            ['role' => 'user', 'content' => $prompt],
        ],
        'temperature' => 0.7,
        'max_tokens' => 1000,
    ];
    return citysyncai_post_to_api('https://api.openai.com/v1/chat/completions', $body, $api_key);
}

// 🔹 Gemini with Multi-Account Support
function citysyncai_call_gemini($type, $city = '') {
    // Get API key(s) with rotation support
    $api_key = citysyncai_get_gemini_api_key();
    
    if (empty($api_key)) {
        return "<p class='citysyncai-error'>Gemini API key not configured. Please add your API key in Settings → CitySyncAI. Get your key at <a href='https://makersuite.google.com/app/apikey' target='_blank'>Google AI Studio</a>.</p>";
    }

    $city_context = $city ? " for {$city}" : '';
    $prompt = "Generate comprehensive, SEO-optimized B2B content for a {$type} page{$city_context} focused on BUSINESS TELECOM SERVICES ONLY (NO residential services). 

Target audience: Businesses spending $1,500-$150,000 per month on telecom services. Focus on enterprise communication solutions, business phone systems, internet connectivity for businesses, cloud services, unified communications, and related business telecom needs.

Write in a professional, B2B-focused tone suitable for business decision-makers and IT managers. Include relevant local business information, economic data, and business-friendly aspects of the area. Emphasize enterprise solutions, reliability, scalability, and cost-effectiveness for businesses.

DO NOT mention residential services, home internet, or consumer-focused offerings. This is exclusively for business-to-business (B2B) services.";
    
    // Use Gemini 1.5 Flash for better cost efficiency (if available) or fallback to gemini-pro
    $model = get_option('citysyncai_gemini_model', 'gemini-1.5-flash');
    $model_map = [
        'gemini-1.5-flash' => 'gemini-1.5-flash',
        'gemini-1.5-pro' => 'gemini-1.5-pro',
        'gemini-pro' => 'gemini-pro',
    ];
    $selected_model = isset($model_map[$model]) ? $model_map[$model] : 'gemini-1.5-flash';
    
    $body = [
        'contents' => [
            [
                'parts' => [
                    ['text' => $prompt]
                ]
            ]
        ],
        'generationConfig' => [
            'temperature' => 0.7,
            'maxOutputTokens' => 2000,
        ]
    ];
    
    return citysyncai_post_to_api("https://generativelanguage.googleapis.com/v1beta/models/{$selected_model}:generateContent?key=" . urlencode($api_key), $body, null, true);
}

/**
 * Get Gemini API key with rotation support
 * Rotates between primary and secondary keys if multi-account is enabled
 *
 * @return string API key
 */
function citysyncai_get_gemini_api_key() {
    $use_multi = get_option('citysyncai_use_multi_account', 'no') === 'yes';
    $key_1 = get_option('citysyncai_gemini_key', '');
    $key_2 = get_option('citysyncai_gemini_key_2', '');
    
    // If multi-account is enabled and both keys exist, rotate
    if ($use_multi && !empty($key_1) && !empty($key_2)) {
        $rotation_count = (int) get_option('citysyncai_gemini_rotation_count', 0);
        $rotation_count++;
        update_option('citysyncai_gemini_rotation_count', $rotation_count);
        
        // Alternate between keys (every request, or you can make it every N requests)
        return ($rotation_count % 2 === 0) ? $key_2 : $key_1;
    }
    
    // Otherwise use primary key
    return $key_1;
}

// 🔹 Claude
function citysyncai_call_claude($type, $city = '') {
    $api_key = get_option('citysyncai_claude_key', '');
    if (empty($api_key)) {
        return "<p class='citysyncai-error'>Claude API key not configured. Please add your API key in Settings → CitySyncAI.</p>";
    }

    $city_context = $city ? " for {$city}" : '';
    $prompt = "Generate SEO-optimized B2B content for a {$type} page{$city_context} targeting BUSINESSES ONLY (NO residential). Focus on enterprise telecom services, business communication solutions, and services for companies spending $1,500-$150,000/month on telecom. Professional tone for business decision-makers.";
    
    $body = [
        'model' => 'claude-3-haiku-20240307', // Using cheaper model
        'max_tokens' => 1000,
        'temperature' => 0.7,
        'messages' => [
            ['role' => 'user', 'content' => $prompt],
        ],
    ];
    return citysyncai_post_to_api('https://api.anthropic.com/v1/messages', $body, $api_key, false, [
        'x-api-key' => $api_key,
        'anthropic-version' => '2023-06-01'
    ]);
}

// 🔹 DeepSeek (VERY AFFORDABLE - Great for bulk generation)
function citysyncai_call_deepseek($type, $city = '') {
    $api_key = get_option('citysyncai_deepseek_key', '');
    if (empty($api_key)) {
        return "<p class='citysyncai-error'>DeepSeek API key not configured. Please add your API key in Settings → CitySyncAI.</p>";
    }

    $city_context = $city ? " for {$city}" : '';
    $prompt = "Generate SEO-optimized B2B content for a {$type} page{$city_context} targeting BUSINESSES ONLY (NO residential). Focus on enterprise telecom services, business communication solutions, and services for companies spending $1,500-$150,000/month on telecom. Professional tone for business decision-makers.";
    
    $body = [
        'model' => 'deepseek-chat',
        'messages' => [
            ['role' => 'system', 'content' => 'You are a helpful SEO assistant specializing in local content creation.'],
            ['role' => 'user', 'content' => $prompt],
        ],
        'temperature' => 0.7,
        'max_tokens' => 2000,
    ];
    return citysyncai_post_to_api('https://api.deepseek.com/v1/chat/completions', $body, $api_key);
}

// 🔹 Genspark
function citysyncai_call_genspark($type, $city = '') {
    $api_key = get_option('citysyncai_genspark_key', '');
    if (empty($api_key)) {
        return "<p class='citysyncai-error'>Genspark API key not configured. Please add your API key in Settings → CitySyncAI.</p>";
    }

    $city_context = $city ? " for {$city}" : '';
    $prompt = "Generate SEO-optimized content for a {$type} page{$city_context} targeting local users.";
    
    $body = [
        'model' => 'genspark-pro',
        'messages' => [
            ['role' => 'user', 'content' => $prompt],
        ],
    ];
    return citysyncai_post_to_api('https://api.genspark.ai/v1/chat/completions', $body, $api_key);
}

// 🔹 Grok
function citysyncai_call_grok($type, $city = '') {
    $api_key = get_option('citysyncai_grok_key', '');
    if (empty($api_key)) {
        return "<p class='citysyncai-error'>Grok API key not configured. Please add your API key in Settings → CitySyncAI.</p>";
    }

    $city_context = $city ? " for {$city}" : '';
    $prompt = "Generate SEO-optimized content for a {$type} page{$city_context} targeting local users.";
    
    $body = [
        'model' => 'grok-beta',
        'messages' => [
            ['role' => 'user', 'content' => $prompt],
        ],
        'temperature' => 0.7,
        'max_tokens' => 1000,
    ];
    return citysyncai_post_to_api('https://api.x.ai/v1/chat/completions', $body, $api_key);
}

// 🔧 Shared API Caller with Enhanced Error Handling
function citysyncai_post_to_api($url, $body, $api_key = null, $is_gemini = false, $custom_headers = []) {
    // Build headers
    if (!empty($custom_headers)) {
        $headers = array_merge(['Content-Type' => 'application/json'], $custom_headers);
    } else {
        $headers = [
            'Content-Type' => 'application/json',
        ];
        if ($api_key && !$is_gemini) {
            $headers['Authorization'] = 'Bearer ' . $api_key;
        }
    }

    $response = wp_remote_post($url, [
        'headers' => $headers,
        'body'    => wp_json_encode($body),
        'timeout' => 30, // Increased timeout for better reliability
    ]);

    // Check for WordPress HTTP errors
    if (is_wp_error($response)) {
        $error_msg = $response->get_error_message();
        citysyncai_log_error("API Request Error: {$error_msg}");
        return "<p class='citysyncai-error'>API Error: " . esc_html($error_msg) . "</p>";
    }

    $response_code = wp_remote_retrieve_response_code($response);
    $response_body = wp_remote_retrieve_body($response);
    $data = json_decode($response_body, true);

    // Check HTTP status code
    if ($response_code !== 200) {
        $error_message = isset($data['error']['message']) ? $data['error']['message'] : 'Unknown error';
        if (isset($data['error'])) {
            $error_message = is_array($data['error']) ? (isset($data['error']['message']) ? $data['error']['message'] : wp_json_encode($data['error'])) : $data['error'];
        }
        citysyncai_log_error("API HTTP Error {$response_code}: {$error_message}");
        return "<p class='citysyncai-error'>API Error ({$response_code}): " . esc_html($error_message) . "</p>";
    }

    // Parse Gemini response
    if ($is_gemini) {
        if (!isset($data['candidates'][0]['content']['parts'][0]['text'])) {
            $error_msg = isset($data['error']['message']) ? $data['error']['message'] : 'No text in Gemini response';
            citysyncai_log_error("Gemini API Error: {$error_msg}");
            citysyncai_log_api_usage('gemini', 'error');
            return "<p class='citysyncai-error'>Gemini API Error: " . esc_html($error_msg) . "</p>";
        }
        citysyncai_log_api_usage('gemini', 'success');
        return wp_kses_post($data['candidates'][0]['content']['parts'][0]['text']);
    }

    // Parse standard OpenAI-compatible response
    if (!isset($data['choices'][0]['message']['content'])) {
        $error_msg = isset($data['error']['message']) ? $data['error']['message'] : 'No content in API response';
        citysyncai_log_error("API Response Error: {$error_msg}");
        // Try to detect provider from URL for logging
        $provider = 'unknown';
        if (strpos($url, 'openai.com') !== false) $provider = 'openai';
        elseif (strpos($url, 'deepseek.com') !== false) $provider = 'deepseek';
        elseif (strpos($url, 'anthropic.com') !== false) $provider = 'claude';
        elseif (strpos($url, 'x.ai') !== false) $provider = 'grok';
        citysyncai_log_api_usage($provider, 'error');
        return "<p class='citysyncai-error'>API Response Error: " . esc_html($error_msg) . "</p>";
    }
    
    // Log successful API usage
    $provider = 'unknown';
    if (strpos($url, 'openai.com') !== false) $provider = 'openai';
    elseif (strpos($url, 'deepseek.com') !== false) $provider = 'deepseek';
    elseif (strpos($url, 'anthropic.com') !== false) $provider = 'claude';
    elseif (strpos($url, 'x.ai') !== false) $provider = 'grok';
    citysyncai_log_api_usage($provider, 'success');

    return wp_kses_post($data['choices'][0]['message']['content']);
}

// Note: Logging is handled by includes/log-engine.php